In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [ ]:
mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.62406299, 0.78345234, 0.62811236, 0.13146507, 0.2386919 ])

In [18]:
np.random.rand(5,5)

array([[0.87172746, 0.67561946, 0.42214557, 0.81792605, 0.24733242],
       [0.41741505, 0.41522544, 0.67358167, 0.51809614, 0.42488006],
       [0.678344  , 0.28550425, 0.2057684 , 0.75581612, 0.15396466],
       [0.41570659, 0.32400846, 0.61508724, 0.08051058, 0.00963766],
       [0.09620749, 0.22112865, 0.51818489, 0.77297645, 0.91653508]])

In [19]:
np.random.randn(2)

array([-0.34590977,  0.88293802])

In [20]:
np.random.randn(4,4)

array([[ 0.30472029, -0.87951103, -0.25274461,  1.08980814],
       [ 0.87269077,  0.56625568,  0.21217161,  0.96233276],
       [ 0.74386224,  2.24445917,  0.77801031, -1.44596381],
       [ 0.95206465, -1.17365209, -0.48127644,  1.65849458]])

In [22]:
np.random.randint(1,100,10)

array([48, 41, 13, 77,  9, 49, 38, 21, 63, 20])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([ 1, 25, 17, 22, 44, 33, 45,  0, 46,  1])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.max()

46

In [32]:
ranarr.argmax()

8

In [33]:
arr.shape

(25,)

In [36]:
arr = arr.reshape(5,5)

In [38]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.shape

(5, 5)

In [39]:
arr.dtype

dtype('int32')