In [21]:
import numpy as np

arr = np.arange(0,11)
print(arr[1])
print(arr[1:5])
print(arr[:6])
print(arr[5:])

slice_of_arr = arr[0:6]

print(slice_of_arr)

slice_of_arr[:] = 99
print(slice_of_arr)

print(arr)#slice_of_arr points to the portion of arr

#for a copy use .copy() method
arr_copy = arr.copy()
print(arr_copy)

print(arr)

arr_copy[:] = 100
print(arr_copy)

print(arr)

1
[1 2 3 4]
[0 1 2 3 4 5]
[ 5  6  7  8  9 10]
[0 1 2 3 4 5]
[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]
[99 99 99 99 99 99  6  7  8  9 10]
[99 99 99 99 99 99  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99 99 99  6  7  8  9 10]


In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
#double brakect format
#arr2d[row] = array
#arr2d[row][col] = position value
print(arr_2d[1][1])

#single bracket format
#arr2d[row,col]
print(arr_2d[1,1])

#grabbing section
#top right corner
print(arr_2d[:2,1:])



25
25
[[10 15]
 [25 30]]


In [35]:
#conditional selection
a = np.arange(1,11)
print(a)
bool_arr = a > 5
print("boolean arr ",bool_arr)
print("a: ",a[bool_arr])

[ 1  2  3  4  5  6  7  8  9 10]
boolean arr  [False False False False False  True  True  True  True  True]
a:  [ 6  7  8  9 10]
